from typing import Protocol

class SimdResult(Protocol):
    def __buffer__(self, flags: int, /) -> memoryview: ...
    def __release_buffer__(self, view: memoryview, /) -> None: ...

def add_f32(a: Buffer, b: Buffer) -> SimdResult: ...
def mul_f32(a: Buffer, b: Buffer) -> SimdResult: ...
def neg_f32(a: Buffer) -> SimdResult: ...
def sum_f32(a: Buffer) -> float: ...  # f64 accumulator for precision

type Buffer = memoryview
